version: '3.8'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=music-app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3333:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: