version: '3.8'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=music-app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3333:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  api:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/music-app
      - ACCESS_TOKEN_SECRET=secret
      - REFRESH_TOKEN_SECRET=secret
      - ACCESS_TOKEN_LIFESPAN=1200s
      - REFRESH_TOKEN_LIFESPAN=10d
      - SERVER_PORT=4747
      - API_URL=localhost:4343
      - FRONT_END_URL=*
      - NODE_ENV=dev
    ports:
      - '4747:4747'
    depends_on:
      - mysql
volumes:
  my-db: